- Concepts:
  - en/Concepts/Diataxis/Diataxis.md
- API:
  - en/API/Swagger Petstore Sample/Swagger Petstore Sample.md
  - Petstore Swagger-UI: en/API/swagger/swagger-ui.md
- Reference:
  - en/Reference/Basic markdown syntax/Basic markdown syntax.md
  - en/Reference/Admonitions.md
  - en/Reference/Code visualization.md
  - en/Reference/Python markdown extensions.md

